### ISSUE TITLE
Is grst/ipymd suitable for Hydrogen-Markdown to Jupyter export?

### ISSUE THREAD

**Issue by kiwi0fruit** [grst/ipymd#20]
At the moment my favourite workflow for interactive notebooks is not Jupyter.
I use Atom editor + Hydrogen to write either:

* Markdown + code blocks insertions of different Jupyter kernels (commonly in Python). I deploy it with Hydrogen to see results instanty right in the document. Then [Knitty-Stitch](https://github.com/kiwi0fruit/knitty) it to `.md.md` or `.html` or `pdf` as static output archive.
* Same as before but it's python code split into cells via Hydrogen markers `# %%`. It has markdown insertions if needed.

And now I think it would be nice to export it not to static format like pdf but to dynamic Jupyter notebook format.

Is it possible with `grst/ipymd`?

To write Markdown-Stitch document with code blocks, then stitch it so that some code blocks are converted to markdown/html mixture (markdown mostly/only actually) and some are just code examples. And some code blocks are *marked for Jupyter* (like <code>``` {.python .iamacell}</code> that is Pandoc default markdown output). And then to convert it to the Jupyter notebook so that only marked code blocks are converted to Jupyter cells (others are left as simple markdown code blocks). And to specify in what language should be the exported notebook (python/R for example).

[This project](https://github.com/aaren/notedown) seems to be able to do this stuff, but do not support metadata and kernels specifications. Your project seem to support metadata and kernel specifications but not pandoc code blocks attributes...

PS
yep, this imagined workflow utilises Jupyter three times but differently... It buggs me a bit... But I'd like to use Pandoc ecosystem and filters for documents processing so I'd like to stick to Stitch.

**Comment by grst** [comment]
Well... in the end you will have to try it out. 

But what I can say is:
* ipymd can read pystitch-compatible markdown (it tried it out with the stitch sample file) 
* ipymd will only evaluate 
~~~
```{python} ...```
~~~
blocks and no
 ~~~
```python ...```
~~~
blocks if that is what you mean by *marked for jupyter*

* the entire jupyter kernelspec can be stored in the rmarkdown document header, e.g. 
```
kernelspec:
  display_name: Python 3
  language: python
  name: python3
```

* what will not work is to read the contents from the stitched `html` file. You will have to re-evaluate all cells in jupyter. Rmarkdown uses some 'magic comments' to store the contents in html which lack in the pystitch variant.

**Comment by kiwi0fruit** [comment]
@grst marked for Jupyter would actually be:
``` {.python .iamacell}
# I'm a Jupyter cell
```
And this is not marked:
``` {.python}
# I' m merely a code example inside markdown cell 'cause I don't have .iamacell
```
That's the standard pandoc format that can be obtained from `.md` to `.md.md` stitching.

I guess reevaluating the whole notebook is not a problem. Actually I did not meant to store HTML output (that is inside overall normal markdown document) in cell output section. I meant to store them inside markdown cells hence html should be valid markdown in theory... If not - reevaluating to the resque + using only compatible html inside markdown cells.

Thanks for response!

**Comment by kiwi0fruit** [comment]
@grst marked for Jupyter would actually be:

`````py
``` {.python .iamacell}
# I'm a Jupyter cell
```
And this is not marked:
``` {.python}
# I' m merely a code example inside markdown cell 'cause I don't have .iamacell
```
`````

That's the standard pandoc format that can be obtained from `.md` to `.md.md` stitching.

I guess reevaluating the whole notebook is not a problem. Actually I did not meant to store HTML output (that is inside overall normal markdown document) in cell output section. I meant to store them inside markdown cells hence html should be valid markdown in theory... If not - reevaluating to the resque + using only compatible html inside markdown cells.

Thanks for response!

**Comment by kiwi0fruit** [comment]
@grst  Looks like `grst/ipymd` would be easy to pipeline with [Knitty](https://github.com/kiwi0fruit/knitty). So I wrote a [specification](https://github.com/kiwi0fruit/knitty/issues/2) that seems to be a working solution.

The only thing left is: what way your package can be installed?

**Comment by grst** [comment]
It is a valid python package, so you should be able to simply do something along the lines of
```
git clone ...
cd ipymd
pip install -e .
```

I just didn't make an own PyPi entry, as I am still waiting that my PR gets eventually merged.

**Comment by kiwi0fruit** [comment]
Thanks!
Something tells me that I end up adding patched ipymd to knitty subfolder
:D Hoping that this subfolder can be removed and replaced with external
dep. some day.

18 янв. 2018 г. 14:57 пользователь "Gregor Sturm" <notifications@github.com>
написал:

**Comment by kiwi0fruit** [comment]
BTW: I guess grst/ipymd can be installed via one-liner:
```
pip install git+https://github.com/grst/ipymd.git
```

**Comment by kiwi0fruit** [comment]
@grst I tested ipymd on `test.md` file:
`````
---
kernelspec:
  display_name: Python 3
  language: python
  name: python3
...

Spellcheck dog.

```{python}
print('!!!')
```

```python
print(111)
```
`````
My CWD is where the file is. Then I run:
```
ipymd test.md --from rmarkdown --to notebook
```
Nothing happens. No errors either. Tried to rename to `test.rmd` - same result.

If I run:
```
ipymd test.md --from markdown --to notebook
```
Then new notebook is created but the output is not as as you descriped above (global metata is set to cell metadata, and the wrong code chunk is converted to the cell).

**Comment by kiwi0fruit** [comment]
I've encountered some unicode bugs with ipymd so I switched to notedown and simply added [metadata support](https://github.com/aaren/notedown/pull/69). As I do not need metadata for every cell - this is OK for export to Jupyter. Also notedown has better support for shell pipelines.

**Comment by grst** [comment]
There are two issues with your test file:

1. the metadata section is incorrect, `...` needs to be changed to `---`
```---
kernelspec:
  display_name: Python 3
  language: python
  name: python3
---
```

2. the extension needs to be `.Rmd` (case sensitive). 

After changing that it worked fine for me. 

But if notedown works for your usecase, then go for it!
