### ISSUE TITLE
Is it possible to open a Rmd file as a notebook in (recent) Jupyter ?

### ISSUE THREAD

**Issue by mwouts** [grst/ipymd#21]
As previously discussed at https://github.com/aaren/notedown/issues/79, I'm not sure the instruction to add
```
c.IPymdContentsManager.format = 'rmarkdown'
```
to jupyter's config is effective in recent jupyter configurations. Could you please confirm? Thanks

**Comment by grst** [comment]
Works for me with jupyter 5.4.1. 

I suspect you choose installation option **(2) Integrated into your local jupyter installation**.

In that case you need to add both lines to your config. 
```
c.NotebookApp.contents_manager_class = 'ipymd.IPymdContentsManager'
c.IPymdContentsManager.format = 'rmarkdown'  # choose the format here
```

**Comment by mwouts** [comment]
I see! Thanks. I will give it a try tonight and confirm.

**Comment by mwouts** [comment]
Splendid! It works, indeed. I'm so impressed!
