### ISSUE TITLE
Incorrect .ipynb > .py > .ipynb roundtrip in simple case

### ISSUE THREAD

**Issue by lebigot** [grst/ipymd#24]
If we have an .ipynb notebook that contains a first Markdown cell:

`First Markdown text.`

Then a second Markdown cell _with two paragraphs_:

```
Second Markdown text…

… with a second paragraph.
```

Then converting to .py and then back to .ipynb fails: the second cell is considered (commented out) code.

**Comment by grst** [comment]
My only contribution to ipymd is the Rmarkdown part, for all other formats you should directly post the issue in rossant/ipymd.
